# Site Settings
locale: "en-CAN"
title: "Hubert Luo"
title_separator: "-"
subtitle: # site tagline that appears below site title in masthead
name: &name "Hubert Luo"
description: &description "Data Scientist at Lazard"
url: https://hLuo27.github.io
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Hubert Luo"
  avatar: "/assets/images/profile.jpg"
  bio: "AI / Investment Banking"
  location: "Toronto, Canada"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/hubertluo/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hluo27"
    - label: "Google Scholar"
      icon: "fab fa-google"
      url: "https://scholar.google.com/citations?user=o-pGk90AAAAJ&hl=en"


#footer:
#  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"


defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sticky: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
